sudo: required
services:
   - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_7b2a18b1bfbe_key -iv $encrypted_7b2a18b1bfbe_iv -in multi-k8s-307502-9ac1ee472e11.json.enc -out multi-k8s-307502-9ac1ee472e11.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-307502-9ac1ee472e11.json
  - gcloud config set project multi-k8s-307502
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_NAME" --password-stdin
  - docker build -t namlt3820/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true namlt3820/react-test npm run test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master